
import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null); // jframe abri no meio da tela
    }
    
    public void openInternet(){
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Ero de conexão.");
        }
    }
    
    public void openCalculadora(){
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMusica = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblSocios = new javax.swing.JLabel();
        lblManutencao = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        lblCronograma = new javax.swing.JLabel();
        lblDrive = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        painelLogin.setForeground(new java.awt.Color(255, 255, 255));
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Password:");
        painelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel4.setBackground(new java.awt.Color(238, 112, 82));
        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 112, 82));
        jLabel4.setText("User:");
        painelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_96px_2.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        painelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 110, 120));
        painelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 220, 10));
        painelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 220, 10));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setBorder(null);
        painelLogin.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_customer_32px_1.png"))); // NOI18N
        painelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_32px.png"))); // NOI18N
        painelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        painelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        painelLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 90, 40));

        lblMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Musical_Notes_32px.png"))); // NOI18N
        lblMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelLogin.add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 200, 50, 40));

        lblInternet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        lblInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInternetMouseClicked(evt);
            }
        });
        painelLogin.add(lblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, 50, 40));

        lblCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        lblCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseClicked(evt);
            }
        });
        painelLogin.add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 50, 40));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setBorder(null);
        painelLogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 40));

        getContentPane().add(painelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Sócios");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Agenda");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Cronograma");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setText("Manutenção");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 99, 71));
        jLabel17.setForeground(new java.awt.Color(255, 99, 71));
        jLabel17.setText("Notas");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 99, 71));
        jLabel18.setForeground(new java.awt.Color(255, 99, 71));
        jLabel18.setText("Drive");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        lblSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Handshake_96px.png"))); // NOI18N
        lblSocios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSociosMouseMoved(evt);
            }
        });
        lblSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSociosMouseExited(evt);
            }
        });
        jPanel1.add(lblSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 210, 170));

        lblManutencao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Maintenance_96px.png"))); // NOI18N
        lblManutencao.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblManutencaoMouseMoved(evt);
            }
        });
        lblManutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManutencaoMouseExited(evt);
            }
        });
        jPanel1.add(lblManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 210, 170));

        lblAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Today_96px.png"))); // NOI18N
        lblAgenda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAgendaMouseMoved(evt);
            }
        });
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgendaMouseExited(evt);
            }
        });
        jPanel1.add(lblAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 170));

        lblNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Idea_96px.png"))); // NOI18N
        lblNotas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblNotasMouseMoved(evt);
            }
        });
        lblNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNotasMouseExited(evt);
            }
        });
        jPanel1.add(lblNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 170));

        lblCronograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Clock_96px.png"))); // NOI18N
        lblCronograma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCronogramaMouseMoved(evt);
            }
        });
        lblCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCronogramaMouseExited(evt);
            }
        });
        jPanel1.add(lblCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 210, 170));

        lblDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Google_Drive_96px.png"))); // NOI18N
        lblDrive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDriveMouseMoved(evt);
            }
        });
        lblDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDriveMouseExited(evt);
            }
        });
        jPanel1.add(lblDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 210, 170));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 40));

        txtPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        txtPesquisa.setForeground(new java.awt.Color(153, 153, 153));
        try {
            txtPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("Busca")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPesquisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 700, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 700, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // adicionamos o animationClass.jar na biblioteca, agora suba la em cima e importe ela - import AppPackage.AnimationClass;
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, lblInternet); 
        /*da esquerda pra direta, o label que voce esta trabalahando, normal e width é a velocidade do movimento,
         *error a posição que o icone vai parar quando clicar, abort é a posiçao atual no frame
         */
        
        //no nosso exemplo vai la nos icones e coloca a posiçao deles -40 pra eles ficarem a esquerda do frame sem aparecer
        
        //cria um novo objeto AnimationClass mas dessa vez o jlabel para a esquerda e inverta a posiçao atual com a final do primeiro obj AnimationClass
        AnimationClass internet2 = new AnimationClass();
        internet2.jLabelXLeft(10, -40, 10, 5, lblInternet); 
        
        //FAÇA ISSO PRO DEMAIS ICONES QUE VOCE QUER QUE SE MOVIMENTE AO CLICAR NO ICONE SELECIONADO (Nesse caso o menu)
        //-----------------------------------------------------------------------
        AnimationClass musica = new AnimationClass();
        musica.jLabelXRight(-40, 10, 10, 5, lblMusica);
        
        AnimationClass musica2 = new AnimationClass();
        musica2.jLabelXLeft(10, -40, 10, 5, lblMusica);
        
        
        AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXRight(-40, 10, 10, 5, lblCalculadora);
        
        AnimationClass calculadora2 = new AnimationClass();
        calculadora2.jLabelXLeft(10, -40, 10, 5, lblCalculadora);
         //-----------------------------------------------------------------------
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Deseja sair do login ?","",dialog);
        
        if (result==0) {
            System.exit(0); // Revisar esse showConfirmDialog depois nao entendi a logica do if
        }
        
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        setState(Login.ICONIFIED); // iconificado/ minimizar a jframe
    }//GEN-LAST:event_jLabel20MouseClicked

    private void lblAgendaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseMoved
        lblAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));  // quando passa o mouse no label ele cria uma borda com a cor setada
        
        //ir no label e criar um evento mouseExit para setar que quando o ponteiro sair a borda saia
    }//GEN-LAST:event_lblAgendaMouseMoved

    private void lblAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseExited
        lblAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));  // quando tira o ponteiro do mouse no label ele cria uma borda com a cor setada/ colocamos branco como era antes
    }//GEN-LAST:event_lblAgendaMouseExited

    private void lblCronogramaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCronogramaMouseMoved
        lblCronograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblCronogramaMouseMoved

    private void lblManutencaoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManutencaoMouseMoved
        lblManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblManutencaoMouseMoved

    private void lblNotasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotasMouseMoved
        lblNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblNotasMouseMoved

    private void lblDriveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDriveMouseMoved
        lblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblDriveMouseMoved

    private void lblSociosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseMoved
        lblSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblSociosMouseMoved

    private void lblCronogramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCronogramaMouseExited
        lblCronograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblCronogramaMouseExited

    private void lblManutencaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManutencaoMouseExited
        lblManutencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblManutencaoMouseExited

    private void lblNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotasMouseExited
        lblNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblNotasMouseExited

    private void lblDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDriveMouseExited
        lblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblDriveMouseExited

    private void lblSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseExited
        lblSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblSociosMouseExited

    private void lblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseClicked
        openInternet();
    }//GEN-LAST:event_lblInternetMouseClicked

    private void lblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseClicked
        try {
           Runtime rt = Runtime.getRuntime();
           Process p = rt.exec("Calc");
           p.waitFor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro de operação, verificar codificação.");
        }
    }//GEN-LAST:event_lblCalculadoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblCronograma;
    private javax.swing.JLabel lblDrive;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblManutencao;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblSocios;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JFormattedTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
